spring:
  datasource:
    url: 환경값에 맞춰서
    slave-list:
      - name: slave_1
        url: 환경값에 맞춰서
      - name: slave_2
        url: 환경값에 맞춰서
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 아이디
    password: 비밀번호

  jpa:
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: create
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        defer-datasource-initialization: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
        open-in-view: false
        show-sql: true
        generate-ddl: true

  #  jpa:
  #    properties:
  #      hibernate:
  #        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  #        format_sql: true
  #        #      ddl-auto: create
  #        ddl-auto: update
  #        defer-datasource-initialization: true
  #        database-platform: org.hibernate.dialect.MySQL8Dialect
  #        dialect: com.ono.omg.config.MySQL8DialectCustom
  #        show_sql: true


  #      database-platform: org.hibernate.dialect.H2Dialect
  #        use_sql_comments: true

# ?? ?? ??
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8080
  servlet:
    encoding:
      charset: utf-8
      enabled: true
      force: true